# Generated by Django 6.0.5 on 2026-05-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_systembroadcast_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemactivitytracker',
            options={},
        ),
        migrations.RemoveField(
            model_name='researchmaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='researchmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemactivitytracker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemactivitytracker',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='systembroadcast',
            name='urgency',
        ),
        migrations.AlterField(
            model_name='systemactivitytracker',
            name='activity_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='systemactivitytracker',
            name='page_url',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
