# Generated by Django 6.0.5 on 2026-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_systemactivitytracker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='access_level',
            field=models.CharField(blank=True, default='Standard Worker', max_length=50),
        ),
    ]
