# Generated by Django 6.0.5 on 2026-05-27 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_supportticket_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='OpsTimetable',
        ),
        migrations.RemoveField(
            model_name='privatesuggestion',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='researchmaterial',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='systemactivitytracker',
            name='user',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='ai_suggested_resolution',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='ai_urgency_rating',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systembroadcast',
            name='is_active',
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default='Legacy', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='title',
            field=models.CharField(default='Support Request', max_length=200),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systembroadcast',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='PrivateSuggestion',
        ),
        migrations.DeleteModel(
            name='ResearchMaterial',
        ),
        migrations.DeleteModel(
            name='SystemActivityTracker',
        ),
    ]
