# Generated by Django 6.0.5 on 2026-05-24 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_timetableevent_announcement_message_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
